### ISSUE TITLE
get_js_window rasies an error

### ISSUE THREAD

**Issue by 0xIslamTaha** [js-next/js-ng#109]
```bash
JS-NG> j.core.executors.tmux.get_js_window('hamda')                                                                                                                                                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/js-ng/jumpscale/core/executors/tmux.py", line 19, in get_js_window
    s = get_js_session()
        └ <function get_js_session at 0x7f29bb8a9268>
  File "/opt/js-ng/jumpscale/core/executors/tmux.py", line 11, in get_js_session
    s = server.find_where({'session_name': JS_SESSION_NAME})
        │                                  └ 'js-ng'
        └ <libtmux.server.Server object at 0x7f29dcec6cc0>
  File "/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/common.py", line 320, in find_where
    return self.where(attrs)[0]
           │          └ {'session_name': 'js-ng'}
           └ <libtmux.server.Server object at 0x7f29dcec6cc0>
  File "/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/common.py", line 351, in where
    return list(filter(by, self.children))
                       │   └ <libtmux.server.Server object at 0x7f29dcec6cc0>
                       └ <function TmuxRelationalObject.where.<locals>.by at 0x7f29dc70e9d8>
  File "/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/server.py", line 188, in sessions
    return self.list_sessions()
           └ <libtmux.server.Server object at 0x7f29dcec6cc0>
  File "/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/server.py", line 183, in list_sessions
    return [Session(server=self, **s) for s in self._sessions]
            │              │                   └ <libtmux.server.Server object at 0x7f29dcec6cc0>
            │              └ <libtmux.server.Server object at 0x7f29dcec6cc0>
            └ <class 'libtmux.session.Session'>
  File "/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/server.py", line 173, in _sessions
    return self._list_sessions()
           └ <libtmux.server.Server object at 0x7f29dcec6cc0>
  File "/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/server.py", line 153, in _list_sessions
    raise exc.LibTmuxException(proc.stderr)
          │                    └ <libtmux.common.tmux_cmd object at 0x7f29dc39fdd8>
          └ <module 'libtmux.exc' from '/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/exc.py'>
libtmux.exc.LibTmuxException: ['no server running on /tmp/tmux-0/default']

['no server running on /tmp/tmux-0/default']

```

**Comment by abom** [comment]
Already fixed by @BolaNasr, see https://github.com/js-next/js-ng/issues/270#issuecomment-638814186.

**Comment by hossnys** [comment]
verified
