### ISSUE TITLE
rmtree raises an error with dir

### ISSUE THREAD

**Issue by 0xIslamTaha** [js-next/js-ng#117]
```python
JS-NG> j.sals.fs.rmtree('/tmp/test')                                                                      
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/js-ng/jumpscale/sals/fs/fs.py", line 420, in rmtree
    if path.is_file() or path.is_link():
AttributeError: 'PosixPath' object has no attribute 'is_link'

'PosixPath' object has no attribute 'is_link'

```

**Comment by abom** [comment]
Fixed [here](https://github.com/js-next/js-ng/pull/101/files#diff-f0db1c87ddb4b585a7c6851c72690d14R420) (still not merged yet).
