### ISSUE TITLE
handle permission errors

### ISSUE THREAD

**Issue by 0xIslamTaha** [js-next/js-ng#120]
```python
for el in j.sals.fs.walk_dirs('/', True): 
     2     print(el) 
```

```
/proc/1/task/1/net
/proc/1/task/1/cwd
/proc/1/task/1/root
/proc/1/task/1/attr
/proc/1/task/1/net/stat
/proc/1/task/1/net/dev_snmp6
/proc/1/task/1/net/netfilter
/proc/1/task/1/attr/selinux
/proc/1/task/1/attr/smack
/proc/1/task/1/attr/apparmor
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/ptpython/repl.py", line 123, in _execute
    code = compile_with_flags(line, 'eval')
    │      │                  └ "for el in j.sals.fs.walk_dirs('/', True):\n    print(el)"
    │      └ <function PythonRepl._execute.<locals>.compile_with_flags at 0x7f03b7927620>
    └ <code object <module> at 0x7f03b79669c0, file "<stdin>", line 1>
  File "/root/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/ptpython/repl.py", line 111, in compile_with_flags
    dont_inherit=True)
File "<stdin>", line 1
    for el in j.sals.fs.walk_dirs('/', True):
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/js-ng/jumpscale/sals/fs/fs.py", line 608, in walk
    if filter_fun(entry):
  File "/opt/js-ng/jumpscale/sals/fs/fs.py", line 41, in is_dir
    return pathlib.Path(path).is_dir()
           │            └ PosixPath('/proc/1/map_files/55a9728ef000-55a97291c000')
           └ <module 'pathlib' from '/usr/lib/python3.7/pathlib.py'>
  File "/usr/lib/python3.7/pathlib.py", line 1351, in is_dir
    return S_ISDIR(self.stat().st_mode)
           │       └ PosixPath('/proc/1/map_files/55a9728ef000-55a97291c000')
           └ <built-in function S_ISDIR>
  File "/usr/lib/python3.7/pathlib.py", line 1161, in stat
    return self._accessor.stat(self)
           │                   └ PosixPath('/proc/1/map_files/55a9728ef000-55a97291c000')
           └ PosixPath('/proc/1/map_files/55a9728ef000-55a97291c000')
PermissionError: [Errno 1] Operation not permitted: '/proc/1/map_files/55a9728ef000-55a97291c000'

[Errno 1] Operation not permitted: **'/proc/1/map_files/55a9728ef000-55a97291c000'**
```

**Comment by hossnys** [comment]
verified
