### ISSUE TITLE
dns client tool library

### ISSUE THREAD

**Issue by xmonader** [js-next/js-ng#151]
to resolve domains

**Comment by xmonader** [comment]
already integrated 8d256f8132edbc815aab99cb093f30672b2e6608

**Comment by Pishoy** [comment]
not sure if that is bug or missy steps :

```
$ sudo /etc/init.d/redis-server start

$ jsng
JS-NG> g = j.servers.gedis.get('testgedis')                                                                                                                            
JS-NG> g.start()                                                                                                                                                       
2020-07-05 11:07:38.297 | INFO     | jumpscale.core.application.application:start:23 - Application gedis is started, process id: 68577
JS-NG> gedis = j.clients.gedis.get("local")          
JS-NG> gedis.list_actors()                                                                                                                                             
```
- got `no attribute` error when start
```
JS-NG> gedis.register_actor("greeter", "/home/osboxes/js-ng/jumpscale/servers/gedis/example_greeter.py")                                                               
2020-07-05 11:11:34.282 | ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - AttributeError: 'GedisClient' object has no attribute 'register_actor'
Traceback (most recent call last):
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/bin/jsng", line 11, in <module>
    load_entry_point('js-ng', 'console_scripts', 'jsng')()
    └ <function load_entry_point at 0x7fd4626354c0>
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fd461b97160>
           └ <Command run>
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fd462be71f0>
         │    └ <function Command.invoke at 0x7fd461b97af0>
         └ <Command run>
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'command': None}
           │   │      │    │           └ <click.core.Context object at 0x7fd462be71f0>
           │   │      │    └ <function run at 0x7fd461b2e0d0>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x7fd461b96c10>
           └ <click.core.Context object at 0x7fd462be71f0>
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'command': None}
           │         └ ()
           └ <function run at 0x7fd461b2e0d0>

  File "/home/osboxes/js-ng/jumpscale/entry_points/jsng.py", line 30, in run
    sys.exit(embed(globals(), locals(), configure=ptconfig, history_filename=HISTORY_FILENAME))
    │   │    │                                    │                          └ '/home/osboxes/.jsng/history.txt'
    │   │    │                                    └ <function ptconfig at 0x7fd4610ff820>
    │   │    └ <function embed at 0x7fd460f9e430>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 350, in embed
    repl.run()
    │    └ <function PythonRepl.run at 0x7fd460f9bf70>
    └ <ptpython.repl.PythonRepl object at 0x7fd4611040d0>
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 74, in run
    self._process_text(text)
    │    │             └ 'gedis.register_actor("greeter", "/home/osboxes/js-ng/jumpscale/servers/gedis/example_greeter.py")'
    │    └ <function PythonRepl._process_text at 0x7fd460f9e040>
    └ <ptpython.repl.PythonRepl object at 0x7fd4611040d0>
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 88, in _process_text
    self._handle_exception(e)
    │    │                 └ AttributeError("'GedisClient' object has no attribute 'register_actor'")
    │    └ functools.partial(<function patched_handle_exception at 0x7fd461b2e430>, <ptpython.repl.PythonRepl object at 0x7fd4611040d0>)
    └ <ptpython.repl.PythonRepl object at 0x7fd4611040d0>
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 163, in _execute
    six.exec_(code, self.get_globals(), self.get_locals())
    │   │     │     │    │              │    └ <function embed.<locals>.get_locals at 0x7fd460f9e4c0>
    │   │     │     │    │              └ <ptpython.repl.PythonRepl object at 0x7fd4611040d0>
    │   │     │     │    └ <function embed.<locals>.get_globals at 0x7fd461b2e310>
    │   │     │     └ <ptpython.repl.PythonRepl object at 0x7fd4611040d0>
    │   │     └ <code object <module> at 0x7fd45f30e190, file "<stdin>", line 1>
    │   └ <built-in function exec>
    └ <module 'six' from '/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/six.py'>
> File "<stdin>", line 1, in <module>

AttributeError: 'GedisClient' object has no attribute 'register_actor'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'GedisClient' object has no attribute 'register_actor'

'GedisClient' object has no attribute 'register_actor'



```

**Comment by xmonader** [comment]
@Pishoy not sure what are you trying to do

```python
JS-NG> j.tools.dnstool.resolver.namerecords_get("google.com")                          
['172.217.21.14']
```

**Comment by Pishoy** [comment]
can not find dnstool 


![image](https://user-images.githubusercontent.com/21987477/86593655-e6b6e680-bf95-11ea-9342-76dfad23e741.png)


```
(js-ng-JVcG1psT-py3.6) root@246413201fd5:~/js-ng# git log -1
commit 07fef6d906b585a64bd59068ba824a1f982cdadb (HEAD -> development, origin/development, origin/HEAD)
Author: Jo De Boeck <deboeck.jo@gmail.com>
Date:   Mon Jul 6 13:47:35 2020 +0200

    Stop threbotserver and all services starts on sigterm/sigint (ctrl-c) (#404)
```

**Comment by xmonader** [comment]
Ah indeed needs to be in js-sdk
