### ISSUE TITLE
old instances from config manager are courrpted if you didn't use save

### ISSUE THREAD

**Issue by waleedhammam** [js-next/js-ng#268]
get an instance, example `s = j.servers.threebot.get("aa") `
exit shell, enter again
get the same instance you will get this error

```
(js-ng-8wc8VQwF-py3.8) ➜  js-ng git:(development_threebot) ✗ jsng
JS-NG> s = j.servers.threebot.get("anyname")                                                          
JS-NG> s.start()                                                                                      
2020-06-02 11:03:02.511 | INFO     | jumpscale.core.application.application:start:17 - Application gedis is started, process id: 156046
2020-06-02 11:03:02.520 | INFO     | jumpscale.servers.gedis.server:stop:209 - Shutting down ...
2020-06-02 11:03:02.523 | INFO     | jumpscale.core.application.application:start:17 - Application gedis is started, process id: 156046
JS-NG>                                                                                                
(js-ng-8wc8VQwF-py3.8) ➜  js-ng git:(development_threebot) ✗ jsng
JS-NG> s = j.servers.threebot.get("anyname")                                                          
Traceback (most recent call last):
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-ng-8wc8VQwF-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 123, in _execute
    code = compile_with_flags(line, 'eval')
    │      │                  └ 's = j.servers.threebot.get("anyname")'
    │      └ <function PythonRepl._execute.<locals>.compile_with_flags at 0x7feedd7001f0>
    └ <code object <module> at 0x7feedd7c4ea0, file "<stdin>", line 1>
  File "/home/waleed/.cache/pypoetry/virtualenvs/js-ng-8wc8VQwF-py3.8/lib/python3.8/site-packages/ptpython/repl.py", line 109, in compile_with_flags
    return compile(code, '<stdin>', mode,
File "<stdin>", line 1
    s = j.servers.threebot.get("anyname")
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/waleed/js-ng/jumpscale/core/base/factory.py", line 198, in get
    instance = self.find(name)
               │         └ 'anyname'
               └ <jumpscale.core.base.factory.jumpscaleserversthreebotthreebotThreebotServer object at 0x7feede2de070>
  File "/home/waleed/js-ng/jumpscale/core/base/factory.py", line 122, in find
    instance = getattr(self, name, None)
                       │     └ 'anyname'
                       └ <jumpscale.core.base.factory.jumpscaleserversthreebotthreebotThreebotServer object at 0x7feede2de070>
  File "/home/waleed/js-ng/jumpscale/core/base/factory.py", line 432, in getter
    instance._set_data(factory.store.get(name))
    │                  │                 └ 'anyname'
    │                  └ <jumpscale.core.base.factory.jumpscaleserversthreebotthreebotThreebotServer object at 0x7feede2de070>
    └ ThreebotServer(_Base__instance_name='anyname', _Base__parent=None, ___package_manager=<jumpscale.core.base.factory.StoredFactory...
  File "/home/waleed/js-ng/jumpscale/core/base/store.py", line 218, in get
    config = json.loads(self.read(instance_name))
             │          │         └ 'anyname'
             │          └ <jumpscale.core.base.store.FileSystemStore object at 0x7feedd727f10>
             └ <module 'jumpscale.data.serializers.json' from '/home/waleed/js-ng/jumpscale/data/serializers/json.py'>
  File "/home/waleed/js-ng/jumpscale/core/base/store.py", line 313, in read
    return read_file_binary(path)
           │                └ '/home/waleed/.config/jumpscale/secureconfig/jumpscale/servers/threebot/threebot/ThreebotServer/anyname/data'
           └ <function read_bytes at 0x7feee0cbcdc0>
  File "/home/waleed/js-ng/jumpscale/sals/fs/__init__.py", line 579, in read_bytes
    return pathlib.Path(path).read_bytes()
           │            └ '/home/waleed/.config/jumpscale/secureconfig/jumpscale/servers/threebot/threebot/ThreebotServer/anyname/data'
           └ <module 'pathlib' from '/usr/lib/python3.8/pathlib.py'>
  File "/usr/lib/python3.8/pathlib.py", line 1220, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/lib/python3.8/pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
           │                   │     │      └ 438
           │                   │     └ 524288
           │                   └ PosixPath('/home/waleed/.config/jumpscale/secureconfig/jumpscale/servers/threebot/threebot/ThreebotServer/anyname/data')
           └ PosixPath('/home/waleed/.config/jumpscale/secureconfig/jumpscale/servers/threebot/threebot/ThreebotServer/anyname/data')
FileNotFoundError: [Errno 2] No such file or directory: '/home/waleed/.config/jumpscale/secureconfig/jumpscale/servers/threebot/threebot/ThreebotServer/anyname/data'

[Errno 2] No such file or directory: '/home/waleed/.config/jumpscale/secureconfig/jumpscale/servers/threebot/threebot/ThreebotServer/anyname/data'
JS-NG>  
```

**Comment by abom** [comment]
This is caused when a sub-factory instance is saved, without saving the parent.

This [commit](https://github.com/js-next/js-ng/commit/57889582edcc4bfe1867a12168218e506e41f072) added a fix where calling `save()` triggers parent's `save()` too.

**Comment by waleedhammam** [comment]
works perfect now, thanks
![Screenshot from 2020-06-02 21-06-39](https://user-images.githubusercontent.com/10658229/83559533-03827900-a515-11ea-927a-05ac5756b11c.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified
