### ISSUE TITLE
Configuration factory fails to delete object

### ISSUE THREAD

**Issue by m-motawea** [js-next/js-ng#293]
stack trace
```
2020-06-08 15:52:01.017 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method report from actor chatflows_chatbot to client ('127.0.0.1', 35462)
2020-06-08 15:52:01.191 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:144 - error
Traceback (most recent call last):

> File "/home/maged/Code/js-ng/jumpscale/sals/chatflows/chatflows.py", line 137, in wrapper
    getattr(self, step_name)()
            │     └ 'network_reservation'
            └ <network_deploy.NetworkDeploy object at 0x7fb1e4137d68>

  File "/home/maged/Code/js-ng/jumpscale/sals/chatflows/chatflows.py", line 578, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<network_deploy.NetworkDeploy object at 0x7fb1e4137d68>,)
           └ <function NetworkDeploy.network_reservation at 0x7fb1e41eab70>

  File "/home/maged/Code/js-sdk/jumpscale/packages/tfgrid_solutions/chats/network_deploy.py", line 36, in network_reservation
    ip_range = j.sals.reservation_chatflow.get_ip_range(self)
               │                                        └ <network_deploy.NetworkDeploy object at 0x7fb1e4137d68>
               └ <jumpscale.god.J object at 0x7fb1ecce4b70>

  File "/home/maged/Code/js-ng/jumpscale/god.py", line 109, in __getattr__
    self._load()
    │    └ <function ExportedModule._load at 0x7fb1eb42fd90>
    └ ExportedModule(__doc__=None, _exportedas=None, _loaded=False, _m=<module 'jumpscale.sals.reservation_chatflow' from '/home/ma...

  File "/home/maged/Code/js-ng/jumpscale/god.py", line 101, in _load
    self._exportedas = self._m.export_module_as()
    │    │             │    │  └ <function export_module_as at 0x7fb1eb3e2620>
    │    │             │    └ <module 'jumpscale.sals.reservation_chatflow' from '/home/maged/Code/js-ng/jumpscale/sals/reservation_chatflow/__init__.py'>
    │    │             └ ExportedModule(__doc__=None, _exportedas=None, _loaded=False, _m=<module 'jumpscale.sals.reservation_chatflow' from '/home/ma...
    │    └ None
    └ ExportedModule(__doc__=None, _exportedas=None, _loaded=False, _m=<module 'jumpscale.sals.reservation_chatflow' from '/home/ma...

  File "/home/maged/Code/js-ng/jumpscale/sals/reservation_chatflow/__init__.py", line 4, in export_module_as
    return ReservationChatflow()
           └ <class 'jumpscale.sals.reservation_chatflow.reservation_chatflow.ReservationChatflow'>

  File "/home/maged/Code/js-ng/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 140, in __init__
    self.get_solutions_explorer()
    │    └ <function ReservationChatflow.get_solutions_explorer at 0x7fb1e40bf1e0>
    └ <jumpscale.sals.reservation_chatflow.reservation_chatflow.ReservationChatflow object at 0x7fb1e4116898>

  File "/home/maged/Code/js-ng/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 255, in get_solutions_explorer
    self.solutions.delete(obj)
    │    │         │      └ 'testnet_460422'
    │    │         └ <function Factory.delete at 0x7fb1e8fc98c8>
    │    └ <jumpscale.core.base.factory.jumpscalesalsreservation_chatflowmodelsTfgridSolution1 object at 0x7fb1e4116860>
    └ <jumpscale.sals.reservation_chatflow.reservation_chatflow.ReservationChatflow object at 0x7fb1e4116898>

  File "/home/maged/Code/js-ng/jumpscale/core/base/factory.py", line 227, in delete
    self._delete_instance(name)
    │    │                └ 'testnet_460422'
    │    └ <function StoredFactory._delete_instance at 0x7fb1e8fcd378>
    └ <jumpscale.core.base.factory.jumpscalesalsreservation_chatflowmodelsTfgridSolution1 object at 0x7fb1e4116860>

  File "/home/maged/Code/js-ng/jumpscale/core/base/factory.py", line 479, in _delete_instance
    super()._delete_instance(name)
                             └ 'testnet_460422'

  File "/home/maged/Code/js-ng/jumpscale/core/base/factory.py", line 214, in _delete_instance
    if hasattr(self, name):
               │     └ 'testnet_460422'
               └ <jumpscale.core.base.factory.jumpscalesalsreservation_chatflowmodelsTfgridSolution1 object at 0x7fb1e4116860>

  File "/home/maged/Code/js-ng/jumpscale/core/base/factory.py", line 436, in getter
    instance._set_data(factory.store.get(name))
    │        │         │       │         └ 'testnet_460422'
    │        │         │       └ <property object at 0x7fb1e8fc6f48>
    │        │         └ <jumpscale.core.base.factory.jumpscalesalsreservation_chatflowmodelsTfgridSolution1 object at 0x7fb1e4116860>
    │        └ <function Base._set_data at 0x7fb1e8fd6f28>
    └ TfgridSolution1(_Base__instance_name='testnet_460422', _Base__parent=None, _factories={})

  File "/home/maged/Code/js-ng/jumpscale/core/base/store.py", line 218, in get
    config = json.loads(self.read(instance_name))
             │    │     │    │    └ 'testnet_460422'
             │    │     │    └ <function FileSystemStore.read at 0x7fb1e8fc7a60>
             │    │     └ <jumpscale.core.base.store.FileSystemStore object at 0x7fb1e4123da0>
             │    └ <function loads at 0x7fb1eccacd08>
             └ <module 'jumpscale.data.serializers.json' from '/home/maged/Code/js-ng/jumpscale/data/serializers/json.py'>

  File "/home/maged/Code/js-ng/jumpscale/core/base/store.py", line 313, in read
    return read_file_binary(path)
           │                └ '/home/maged/.config/jumpscale/secureconfig/jumpscale/sals/reservation_chatflow/models/TfgridSolution1/testnet_460422/data'
           └ <function read_bytes at 0x7fb1eb3b47b8>

  File "/home/maged/Code/js-ng/jumpscale/sals/fs/__init__.py", line 579, in read_bytes
    return pathlib.Path(path).read_bytes()
           │       │    └ '/home/maged/.config/jumpscale/secureconfig/jumpscale/sals/reservation_chatflow/models/TfgridSolution1/testnet_460422/data'
           │       └ <class 'pathlib.Path'>
           └ <module 'pathlib' from '/usr/lib/python3.6/pathlib.py'>

  File "/usr/lib/python3.6/pathlib.py", line 1189, in read_bytes
    with self.open(mode='rb') as f:
         │    └ <function Path.open at 0x7fb1ecce98c8>
         └ PosixPath('/home/maged/.config/jumpscale/secureconfig/jumpscale/sals/reservation_chatflow/models/TfgridSolution1/testnet_4604...
  File "/usr/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
           │    └ <function Path._opener at 0x7fb1ecce91e0>
           └ PosixPath('/home/maged/.config/jumpscale/secureconfig/jumpscale/sals/reservation_chatflow/models/TfgridSolution1/testnet_4604...
  File "/usr/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
           │    │              │     │      └ 438
           │    │              │     └ 524288
           │    │              └ PosixPath('/home/maged/.config/jumpscale/secureconfig/jumpscale/sals/reservation_chatflow/models/TfgridSolution1/testnet_4604...
           │    └ <member '_accessor' of 'Path' objects>
           └ PosixPath('/home/maged/.config/jumpscale/secureconfig/jumpscale/sals/reservation_chatflow/models/TfgridSolution1/testnet_4604...
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
           │           │          └ (524288, 438)
           │           └ PosixPath('/home/maged/.config/jumpscale/secureconfig/jumpscale/sals/reservation_chatflow/models/TfgridSolution1/testnet_4604...
           └ <built-in function open>

FileNotFoundError: [Errno 2] No such file or directory: '/home/maged/.config/jumpscale/secureconfig/jumpscale/sals/reservation_chatflow/models/TfgridSolution1/testnet_460422/data'
127.0.0.1 - - [2020-06-08 15:52:01] "POST /chatflows/chatbot/report HTTP/1.0" 200 138 0.200038

```

**Comment by abom** [comment]
This mostly happens when an instance is lazy-loaded, when it's available as a property in the factory, but it's not actually loaded because it has not been accessed.

Trying to resolve this.

**Comment by waleedhammam** [comment]
Works fine now, thanks
