### ISSUE TITLE
allow empty fields in models

### ISSUE THREAD

**Issue by waleedhammam** [js-next/js-ng#301]
we can add an option to all fields

allow_none

and allow_empty

**Comment by abom** [comment]
allow_none is already supported via `required` option.
For `String` based fields, I added `allow_empty` at https://github.com/js-next/js-ng/commit/2f98afd89bf0bde429761cb7de139495f6a528aa.

**Comment by abom** [comment]
Added more tests too at https://github.com/js-next/js-ng/commit/f80f588596a4921f86c186d99a6f165c6a3cf241.

**Comment by waleedhammam** [comment]
```
Traceback (most recent call last):

  File "/home/waleed/js-ng/jumpscale/core/base/meta.py", line 343, in _set_data
    setattr(self, name, value)
            │     │     └ None
            │     └ 'public_config'
            └ TfgridDirectoryNode2(_Base__instance_name=None, _Base__parent=None, __address='', __created=datetime.date(1970, 1, 1), __farm...

  File "/home/waleed/js-ng/jumpscale/core/base/meta.py", line 152, in setter
    value._set_parent(self)
    │                 └ TfgridDirectoryNode2(_Base__instance_name=None, _Base__parent=None, __address='', __created=datetime.date(1970, 1, 1), __farm...
    └ None

AttributeError: 'NoneType' object has no attribute '_set_parent'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'network_selection'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e615bf940>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'solution_name'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e615bf9d0>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'setup_type'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e615bf820>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'storage_type'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e615d0790>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'access_credentials'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e615bfa60>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'container_resources'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e615bff70>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'minio_resources'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e615d0700>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'public_key'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e61506ca0>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'expiration_time'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e61506dc0>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 152, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7f7e61d6daf0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 160, in _execute_current_step
    wrapper(step_name)
    │       └ 'zdb_nodes'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7f7e61506f70>

> File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 137, in wrapper
    getattr(self, step_name)()
            │     └ 'zdb_nodes'
            └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/chatflows/chatflows.py", line 598, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<minio_deploy.MinioDeploy object at 0x7f7e615c3d30>,)
           └ <function MinioDeploy.zdb_nodes at 0x7f7e61d7faf0>

  File "/home/waleed/js-sdk/jumpscale/packages/tfgrid_solutions/chats/minio_deploy.py", line 152, in zdb_nodes
    self.nodes_selected = j.sals.reservation_chatflow.get_nodes(
    │                     └ <jumpscale.god.J object at 0x7f7e675229d0>
    └ <minio_deploy.MinioDeploy object at 0x7f7e615c3d30>

  File "/home/waleed/js-ng/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 918, in get_nodes
    nodes = self.filter_nodes(nodes, currency == "FreeTFT")
    │       │    │            │      └ 'FreeTFT'
    │       │    │            └ <generator object NodeFinder.nodes_by_capacity at 0x7f7e61d84c10>
    │       │    └ <function ReservationChatflow.filter_nodes at 0x7f7e615069d0>
    │       └ <jumpscale.sals.reservation_chatflow.reservation_chatflow.ReservationChatflow object at 0x7f7e615c5c40>
    └ <generator object NodeFinder.nodes_by_capacity at 0x7f7e61d84c10>

  File "/home/waleed/js-ng/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 933, in filter_nodes
    nodes = list(nodes)
    │            └ <filter object at 0x7f7e614d49a0>
    └ <filter object at 0x7f7e614d49a0>

  File "/home/waleed/js-ng/jumpscale/sals/zos/node_finder.py", line 55, in nodes_by_capacity
    nodes = self.nodes_search(farm_id=farm_id, farm_name=farm_name, country=country, city=city)
            │    │            │       │        │         │          │       │        │    └ None
            │    │            │       │        │         │          │       │        └ None
            │    │            │       │        │         │          │       └ None
            │    │            │       │        │         │          └ None
            │    │            │       │        │         └ None
            │    │            │       │        └ None
            │    │            │       └ None
            │    │            └ None
            │    └ <function NodeFinder.nodes_search at 0x7f7e614b3160>
            └ <jumpscale.sals.zos.node_finder.NodeFinder object at 0x7f7e614a6ac0>

  File "/home/waleed/js-ng/jumpscale/sals/zos/node_finder.py", line 101, in nodes_search
    return self._nodes.list(farm_id=farm_id, country=country, city=city, cru=cru, sru=sru, mru=mru, hru=hru)
           │    │      │    │       │        │       │        │    │     │   │    │   │    │   │    │   └ None
           │    │      │    │       │        │       │        │    │     │   │    │   │    │   │    └ None
           │    │      │    │       │        │       │        │    │     │   │    │   │    │   └ None
           │    │      │    │       │        │       │        │    │     │   │    │   │    └ None
           │    │      │    │       │        │       │        │    │     │   │    │   └ None
           │    │      │    │       │        │       │        │    │     │   │    └ None
           │    │      │    │       │        │       │        │    │     │   └ None
           │    │      │    │       │        │       │        │    │     └ None
           │    │      │    │       │        │       │        │    └ None
           │    │      │    │       │        │       │        └ None
           │    │      │    │       │        │       └ None
           │    │      │    │       │        └ None
           │    │      │    │       └ None
           │    │      │    └ None
           │    │      └ <function Nodes.list at 0x7f7e646534c0>
           │    └ <jumpscale.clients.explorer.nodes.Nodes object at 0x7f7e6151f1c0>
           └ <jumpscale.sals.zos.node_finder.NodeFinder object at 0x7f7e614a6ac0>

  File "/home/waleed/js-ng/jumpscale/clients/explorer/nodes.py", line 41, in list
    nodes = list(self.iter(farm_id, country, city, cru, sru, mru, hru, proofs))
                 │    │    │        │        │     │    │    │    │    └ False
                 │    │    │        │        │     │    │    │    └ None
                 │    │    │        │        │     │    │    └ None
                 │    │    │        │        │     │    └ None
                 │    │    │        │        │     └ None
                 │    │    │        │        └ None
                 │    │    │        └ None
                 │    │    └ None
                 │    └ <function Nodes.iter at 0x7f7e64653550>
                 └ <jumpscale.clients.explorer.nodes.Nodes object at 0x7f7e6151f1c0>

  File "/home/waleed/js-ng/jumpscale/clients/explorer/nodes.py", line 48, in iter
    yield from get_all(self._session, TfgridDirectoryNode2, url, query)
               │       │    │         │                     │    └ {}
               │       │    │         │                     └ 'https://explorer.testnet.grid.tf/explorer/nodes'
               │       │    │         └ <class 'jumpscale.clients.explorer.models.TfgridDirectoryNode2'>
               │       │    └ <requests.sessions.Session object at 0x7f7e6151d7f0>
               │       └ <jumpscale.clients.explorer.nodes.Nodes object at 0x7f7e6151f1c0>
               └ <function get_all at 0x7f7e64720160>

  File "/home/waleed/js-ng/jumpscale/clients/explorer/pagination.py", line 15, in get_all
    iter, pages = get_page(session, 1, model, url, query)
                  │        │           │      │    └ {}
                  │        │           │      └ 'https://explorer.testnet.grid.tf/explorer/nodes'
                  │        │           └ <class 'jumpscale.clients.explorer.models.TfgridDirectoryNode2'>
                  │        └ <requests.sessions.Session object at 0x7f7e6151d7f0>
                  └ <function get_page at 0x7f7e647200d0>

  File "/home/waleed/js-ng/jumpscale/clients/explorer/pagination.py", line 8, in get_page
    obj = model.from_dict(data)
          │     │         └ {'id': 1, 'node_id': 'HT9yNvHRQs65dyRJeztAdEnXKweCX2bhgvD9i1WFPUNs', 'hostname': '', 'node_id_v1': '544546f60261', 'farm_id':...
          │     └ <classmethod object at 0x7f7e66b1ba60>
          └ <class 'jumpscale.clients.explorer.models.TfgridDirectoryNode2'>

  File "/home/waleed/js-ng/jumpscale/core/base/meta.py", line 415, in from_dict
    return cls(**data)
           │     └ {'id': 1, 'node_id': 'HT9yNvHRQs65dyRJeztAdEnXKweCX2bhgvD9i1WFPUNs', 'hostname': '', 'node_id_v1': '544546f60261', 'farm_id':...
           └ <class 'jumpscale.clients.explorer.models.TfgridDirectoryNode2'>

  File "/home/waleed/js-ng/jumpscale/core/base/meta.py", line 257, in __init__
    self._set_data(values)
    │    │         └ {'id': 1, 'node_id': 'HT9yNvHRQs65dyRJeztAdEnXKweCX2bhgvD9i1WFPUNs', 'hostname': '', 'node_id_v1': '544546f60261', 'farm_id':...
    │    └ <function Base._set_data at 0x7f7e66961b80>
    └ TfgridDirectoryNode2(_Base__instance_name=None, _Base__parent=None, __address='', __created=datetime.date(1970, 1, 1), __farm...

  File "/home/waleed/js-ng/jumpscale/core/base/meta.py", line 344, in _set_data
    except (fields.ValidationError, ValueError):
            └ {'node_id': <jumpscale.core.base.fields.String object at 0x7f7e6462c4c0>, 'node_id_v1': <jumpscale.core.base.fields.String ob...

AttributeError: 'dict' object has no attribute 'ValidationError'

```

**Comment by waleedhammam** [comment]
also fixed, thanks https://github.com/js-next/js-ng/commit/04297b0a71f4fc5b8004b8e6f09f73ba3656486e
