### ISSUE TITLE
Jumpscale loading not working properly

### ISSUE THREAD

**Issue by alichaddad** [js-next/js-ng#96]
In a jsng try any command from history or copy and paste and you will have the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chaddad/sandbox/code/github/js-next/js-ng/jumpscale/god.py", line 158, in exceptions
    return self.__loaded_dict['jumpscale']['core']['exceptions']
           -> <jumpscale.god.J object at 0x7f55b78f9c18>
KeyError: 'jumpscale'

'jumpscale'
```
This won't happen if you use shell completion or access the `j` god object before.

**Comment by xmonader** [comment]
not an issue anymore

**Comment by hossnys** [comment]
verified
